data:
  path: './data/l63_train.npz'
  n_samples: 1
  n_steps: 2048
  double_precision: true

data_valid:
  path: './data/l63_valid.npz'
  n_samples: 2
  n_steps: 2000
  double_precision: true

transform_x:
  type: "scaler"
  mode: "std"

split:
  train_frac: 1.0

dataloader:
  batch_size: 1

criterion:
  vpt:
    type: "vpt"
    params:
      gamma: 0.3
