data:
  path: './data/ltg.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'ltg_lti_wf'
  encoder_layers: 1
  decoder_layers: 1
  latent_dimension: 32
  koopman_dimension: 3
  const_term: true
  autoencoder_type: "cat"
  gcl: "sage"
  activation: "none"
  weight_init: "xavier_uniform"
  input_order: "cubic"

criterion:
  dynamics:
    weight: 1.0
  recon:
    weight: 1.0

training:
  n_epochs: 500
  save_interval: 10
  load_checkpoint: false
  learning_rate: 5e-3
  weak_form_params:
    N: 13
    dN: 2
    ordpol: 2
    ordint: 2
