data:
  path: './data/ltg.npz'
  n_samples: 32
  n_steps: 501
  double_precision: true

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 4

model:
  name: 'ltg_kbf_wf'
  encoder_layers: 1
  decoder_layers: 1
  latent_dimension: 32
  koopman_dimension: 4
  const_term: true
  autoencoder_type: "smp"
  gcl: "sage"
  activation: "none"
  weight_init: "xavier_uniform"
  input_order: "cubic"

criterion:
  dynamics:
    weight: 1.0
  recon:
    weight: 1.0

training:
  n_epochs: 200
  save_interval: 20
  load_checkpoint: false
  learning_rate: 1e-2
  reconstruction_weight: 1.0
  dynamics_weight: 1.0 
  weak_form_params:
    N: 13
    dN: 2
    ordpol: 2
    ordint: 2
