data:
  path: './data/dyn.npz'
  n_samples: 32
  n_steps: 101
  double_precision: true

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 256
