data:
  path: './data/ltga.npz'
  n_samples: 128
  n_steps: 501
  double_precision: true

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 128

model:
  name: 'ltga_model'
  encoder_layers: 0
  processor_layers: 1
  decoder_layers: 0
  hidden_dimension: 64
  activation: "tanh"
  weight_init: "xavier_uniform"

criterion:
  dynamics:
    weight: 1.0
  recon:
    weight: 1.0

training:
  n_epochs: 500
  save_interval: 10
  load_checkpoint: false
  learning_rate: 1e-2
  decay_rate: 0.999
  weak_form_params:
    N: 13
    dN: 2
    ordpol: 2
    ordint: 2
