data:
  path: './data/lti.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'lti_kbf_mcri'
  encoder_layers: 1
  decoder_layers: 1
  latent_dimension: 32
  koopman_dimension: 4
  const_term: true
  activation: "none"
  weight_init: "xavier_uniform"
  input_order: "cubic"

criterion:
  dynamics:
    type: 'mse'
    weight: 1.0
    params:
      reduction: 'mean'
  recon:
    type: 'mse'
    weight: 1.0
    params:
      reduction: 'mean'

prediction_criterion:
  type: 'wmse'
  params:
    alpha: 0.5

phases:
  - trainer: 'Weak'
    n_epochs: 200
    save_interval: 10
    learning_rate: 5e-3
    weak_form_params:
      N: 13
      dN: 2
      ordpol: 2
      ordint: 2

  - trainer: 'NODE'
    n_epochs: 50
    save_interval: 10
    learning_rate: 5e-3
    decay_rate: 0.999
    sweep_lengths: [300]
    sweep_epoch_step: 200
    ode_method: 'dopri5'
    ode_args:
      rtol: 1.e-7
      atol: 1.e-9
