data:
  path: './data/ltd.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  - type: "scaler"
    mode: "std"
  - type: "delay"
    delay: 1

transform_u:
  type: "delay"
  delay: 1

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'ltd_sdm_smp'
  autoencoder_type: 'seq_smp'
  encoder_layers: 1
  decoder_layers: 1
  processor_type: 'mlp_smp'
  processor_layers: 1
  hidden_dimension: 16
  latent_dimension: 6
  activation: "none"
  weight_init: "xavier_uniform"
  gain: 0.01

criterion:
  dynamics:
    weight: 1.0
  recon:
    weight: 1.0

training:
  n_epochs: 500
  save_interval: 10
  load_checkpoint: false
  learning_rate: 5e-3
  decay_rate: 0.999
  # sweep_lengths: [50, 100, 200, 300, 501]
  sweep_lengths: [4, 8, 16, 32]
  sweep_epoch_step: 100
  chop_mode: "unfold"
  chop_step: 0.5
