data:
  path: './data/ltd.npz'
  n_samples: 128
  n_steps: 501
  double_precision: false

transform_x:
  type: "delay"
  delay: 1

transform_u:
  type: "delay"
  delay: 1

split:
  train_frac: 0.75

dataloader:
  batch_size: 64

model:
  name: 'ltd_lti_node'
  encoder_layers: 1
  decoder_layers: 1
  koopman_dimension: 8
  activation: "none"
  weight_init: "xavier_uniform"
  gain: 0.01
  predictor_type: "np"

criterion:
  dynamics:
    weight: 1.0
  recon:
    weight: 1.0

training:
  n_epochs: 600
  save_interval: 10
  load_checkpoint: false
  learning_rate: 5e-3
  decay_rate: 0.999
  chop_mode: "unfold"
  chop_step: 0.5
  sweep_lengths: [3, 5, 7]
  sweep_epoch_step: 200
