data:
  path: './data/sa.npz'
  n_samples: 500
  n_steps: 41
  double_precision: true

transform_x:
  type: "scaler"
  mode: "-11"

transform_u:
  type: "identity"

split:
  train_frac: 0.8

dataloader:
  batch_size: 300
