data:
  path: './data/ker.npz'
  n_samples: 2
  n_steps: 101
  double_precision: true

transform_x:
  type: "identity"

transform_u:
  type: "identity"

split:
  train_frac: 1.0

dataloader:
  batch_size: 2
